### ISSUE TITLE
Grapple attack bonus calculation is wrong for Tiny or lower creatures

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#867]
If the creature's size is Small or higher, the  3.5SRD system uses Strength modifier for grapple. But, if the creature's size is Tiny or lower, the system uses Dexterity modifier for grapple.

According to the rules, for all creatures the attack bonus on grapple checks should be: Base attack bonus + Strength modifier + special size modifier.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99

**Comment by ilore** [comment]
I still have the issue. I´m using system version 0.99.1 and FVTT V9 242.
